const test=require('node:test'),assert=require('node:assert/strict'),M=require('../app/src/main/assets/model.js'),T=require('../app/src/main/assets/training.js'),Timer=require('../app/src/main/assets/timer.js'),seed=require('../app/src/main/assets/seed.json');
const fixture=()=>M.clone(seed),entry=(s,name)=>s.catalog.find(e=>e.name===name).id;
function plan(s,eid,fields={}){return {exerciseId:eid,...T.settings(s,eid).prescription,enabled:true,restSec:120,group:'',...fields};}
function record(s,eid,w,r,type='working',kind='total',rir=null){M.select(s,eid);Object.assign(s.active.draft,{weight:w,reps:r,type,kind,restSec:0,rir});return M.complete(s);}
function session(s,id,date,sets){return {id,date,title:'Fictional test',muscles:['胸'],exercises:[{exerciseId:entry(s,'杠铃卧推'),sets:sets.map((x,i)=>({id:id+i,complex:false,weight:20,reps:10,kind:'total',unit:'kg',restSec:120,variant:'',...x}))}],startedAt:100,endedAt:600100};}
test('editable three and five split templates deduplicate and preserve order on start',()=>{const s=fixture();assert.equal(T.presets(s,'three',1),6);assert.equal(T.presets(s,'three',2),0);assert.equal(T.presets(s,'five',3),5);const t=s.templates[0],ids=t.entries.map(e=>e.exerciseId);t.entries.reverse();T.saveTemplate(s,t,4);T.applyTemplate(s,t,M);assert.deepEqual(s.active.exercises.map(e=>e.exerciseId),ids.reverse());assert.equal(s.active.draft.restSec,150);assert.throws(()=>T.applyTemplate(s,t,M));assert.equal(s.active.templateId,t.id);const old=s.active.exercises[0].plan.sets;t.entries[0].sets=5;T.saveTemplate(s,t,5);assert.equal(s.active.exercises[0].plan.sets,old);M.validate(s);});
test('invalid templates and action settings never mutate a valid document',()=>{const s=fixture(),eid=entry(s,'杠铃卧推'),before=JSON.stringify(s);assert.throws(()=>T.saveTemplate(s,{name:'one',muscles:['胸'],entries:[plan(s,eid,{group:'A'})]}));assert.equal(JSON.stringify(s),before);assert.throws(()=>T.configure(s,eid,{restSec:-1}));assert.equal(JSON.stringify(s),before);assert.throws(()=>T.saveTemplate(s,{name:'',muscles:['胸'],entries:[plan(s,eid)]}));});
test('superset automatically advances and starts rest only after all members in a round',()=>{const s=fixture(),a=entry(s,'杠铃卧推'),b=entry(s,'蝴蝶机夹胸');const t=T.saveTemplate(s,{name:'super',muscles:['胸'],entries:[plan(s,a,{sets:2,group:'A',restSec:60}),plan(s,b,{sets:2,group:'A',restSec:120})]});T.applyTemplate(s,t,M);Object.assign(s.active.draft,{weight:20,reps:12});M.complete(s);assert.equal(s.active.currentExerciseId,b);assert.equal(s.active.superWaiting,'A');assert.equal(s.restTimer.status,'idle');Object.assign(s.active.draft,{weight:10,reps:12});M.complete(s);assert.equal(s.active.currentExerciseId,a);assert.equal(s.active.superWaiting,null);assert.equal(s.restTimer.durationSec,120);assert.equal(s.restTimer.status,'running');M.complete(s);assert.equal(s.active.currentExerciseId,b);assert.equal(s.restTimer.status,'idle');M.complete(s);assert.equal(s.active.exercises[0].sets.length,2);assert.equal(s.active.exercises[1].sets.length,2);assert.equal(s.restTimer.status,'running');M.validate(s);});
test('planned formal set completion skips to next action; warmups do not finish the plan',()=>{const s=fixture(),a=entry(s,'杠铃卧推'),b=entry(s,'蝴蝶机夹胸');T.applyTemplate(s,T.saveTemplate(s,{name:'flow',muscles:['胸'],entries:[plan(s,a,{sets:1}),plan(s,b,{sets:1})]}),M);record(s,a,20,10,'warmup');assert.equal(s.active.currentExerciseId,a);record(s,a,40,10);assert.equal(s.active.currentExerciseId,b);});
test('quick copying never fills an unknown unit as kg or duplicates RIR and feelings',()=>{const s=fixture(),eid=entry(s,'杠铃卧推');M.begin(s,['胸'],[eid]);T.useSet(s,eid,{weight:19,unit:null,reps:7,kind:'recorded',rir:1,feeling:'吃力',note:'foo'});assert.equal(s.active.draft.weight,'');assert.equal(s.active.draft.reps,7);assert.equal(s.active.draft.rir,null);assert.equal(s.active.draft.feeling,'');assert.throws(()=>T.useSet(s,eid,{complex:true}));T.configure(s,eid,{restSec:90});assert.equal(M.draft(s,eid).restSec,90);});
test('progression requires latest planned working sets, same basis, grip and load',()=>{const s=fixture(),eid=entry(s,'杠铃卧推');T.configure(s,eid,{prescription:{enabled:true,sets:3,minReps:8,maxReps:12,increment:2.5,kind:'total',variant:''}});M.begin(s,['胸'],[eid]);for(let i=0;i<3;i++)record(s,eid,40,12);assert.equal(T.suggestion(s,eid).weight,42.5);record(s,eid,40,8);assert.equal(T.suggestion(s,eid).met,false);record(s,eid,40,12,'warmup');assert.equal(T.suggestion(s,eid).met,false);record(s,eid,20,12,'working','side');assert.equal(T.suggestion(s,eid).met,false);});
test('weekly formal sets, volume, actual PR, durations and RIR keep unknown values distinct',()=>{const s=fixture(),eid=entry(s,'杠铃卧推'),today=M.day();s.sessions.push(session(s,'a',today,[{weight:40,type:'working',rir:2},{weight:100,type:'warmup'},{weight:70,type:'drop'},{weight:90,type:undefined},{weight:999,unit:null,type:'working'},{weight:50,kind:'side',type:'working'},{weight:40,type:'working',rir:null}]));const a=T.analysis(s,eid,'total','',today);assert.equal(a.counts.working,4);assert.equal(a.counts.unknown,1);assert.equal(a.bestWeight.set.weight,90);assert.equal(a.volumes[0].value,800);assert.equal(a.muscles['胸'],4);assert.equal(a.durations[0].minutes,10);assert.equal(a.rir.length,1);assert.equal(a.rir[0].rir,2);
});
test('RIR only compares known estimates at the same most recent load',()=>{const s=fixture(),eid=entry(s,'杠铃卧推');s.sessions.push(session(s,'a','2000-01-01',[{weight:20,type:'working',rir:2}]),session(s,'b','2000-01-02',[{weight:30,type:'working',rir:null},{weight:30,type:'working',rir:5}]));const a=T.analysis(s,eid,'total');assert.equal(a.load,30);assert.equal(a.rir.length,1);assert.equal(a.rir[0].rir,5);});
test('training, PR and weekly rewards are unique; initial-session ramping is not a PR',()=>{const s=fixture();s.preferences.weeklyGoal=2;s.sessions.push(session(s,'a','2000-01-03',[{weight:20},{weight:40}]),session(s,'b','2000-01-04',[{weight:45}]),session(s,'c','2000-01-05',[{weight:999,type:'warmup'},{weight:45}]));assert.equal(T.reward(s),55);assert(!s.pet.ledger.some(x=>x.id==='pr:a'));assert.equal(T.reward(s),0);assert.equal(T.balance(s),55);assert(T.purchase(s,'bowl'));assert.equal(T.balance(s),15);assert.equal(T.purchase(s,'bowl'),false);T.furniture(s,'bowl');assert.deepEqual(s.pet.furniture,['bowl']);T.feed(s,'2000-01-06');assert.equal(T.balance(s),13);assert.throws(()=>T.feed(s,'2000-01-06'));assert.throws(()=>T.purchase(s,'cape'));M.validate(s);});
test('backup merge keeps newer template/settings and deduplicates pet ledger',()=>{const local=fixture(),eid=entry(local,'杠铃卧推');T.configure(local,eid,{favorite:true},20);T.saveTemplate(local,{id:'t',name:'local',muscles:['胸'],entries:[plan(local,eid)]},20);const incoming=M.clone(local);T.configure(incoming,eid,{favorite:false},10);incoming.templates[0].name='older';incoming.templates[0].modifiedAt=10;incoming.pet.ledger.push({id:'training:example',amount:10,label:'test',date:'2000-01-01',createdAt:1});let out=M.merge(local,incoming).state;assert.equal(out.exerciseSettings[eid].favorite,true);assert.equal(out.templates[0].name,'local');out=M.merge(out,incoming).state;assert.equal(T.balance(out),10);T.archiveTemplate(out,'t',30);assert.equal(M.merge(out,local).state.templates[0].archived,true);});
test('Markdown options and CSV preserve group types, supersets and RIR without inventing estimates',()=>{const s=fixture();s.sessions.push(session(s,'a','2000-01-01',[{type:'working',rir:5,superGroup:'A'}]));assert.match(M.exportMarkdown(s),/正式组 \/ 超级组A/);assert.match(M.exportMarkdown(s),/RIR 5\+/);assert.match(M.exportCsv(s),/"5\+"/);const md=M.exportMarkdown(s,'','9999-12-31',{sets:false,goals:false,original:false,analysis:false});assert(!md.includes('RIR'));assert(!md.includes('20 kg'));assert(!md.includes('训练结构与动作计划'));});
test('timer native control revision survives all JS operations and rejects invalid revisions',()=>{const t={...Timer.blank(),controlRevision:7};for(const next of [Timer.start(t),Timer.reset(t),Timer.select(t,60),Timer.adjust(t,15)])assert.equal(next.controlRevision,7);assert.throws(()=>Timer.validate({...t,controlRevision:-1}));});
test('unequal superset goals finish a shared round then let the remaining action rest alone',()=>{const s=fixture(),a=entry(s,'杠铃卧推'),b=entry(s,'蝴蝶机夹胸');T.applyTemplate(s,T.saveTemplate(s,{name:'unequal',muscles:['胸'],entries:[plan(s,a,{sets:1,group:'A',restSec:180}),plan(s,b,{sets:3,group:'A',restSec:60})]}),M);Object.assign(s.active.draft,{weight:20,reps:10});M.complete(s);assert.equal(s.active.currentExerciseId,b);Object.assign(s.active.draft,{weight:10,reps:10});M.complete(s);assert.equal(s.restTimer.durationSec,180);assert.equal(s.active.currentExerciseId,b);M.complete(s);assert.equal(s.restTimer.durationSec,60);assert.equal(s.active.superWaiting,null);assert.equal(s.active.exercises[0].sets.length,1);M.complete(s);assert.equal(s.active.exercises[1].sets.length,3);});
